import logging

import vertexai
from vertexai.generative_models import FunctionDeclaration, GenerativeModel, Part, Tool

from .config import Config


# Initialize logger
logger = logging.getLogger(__name__)


class Agent:
    """Orchestrates the LLM reasoning loop and tool execution."""

    def __init__(self, config: Config, search_func):
        """Sets up Vertex AI, tools, and the generative model."""
        self.config = config
        self.search_func = search_func

        vertexai.init(project=self.config.PROJECT_ID, location=self.config.LOCATION)

        search_tool = Tool(
            function_declarations=[
                FunctionDeclaration(
                    name='search_docs',
                    description='Search in university documents for academic knowledge.',
                    parameters={
                        'type': 'object',
                        'properties': {
                            'query': {'type': 'string', 'description': 'Search term'}
                        },
                        'required': ['query'],
                    },
                )
            ]
        )
        generation_config = {
            'temperature': 0.1,  # Low -> Strict, less creativity
            'top_p': 0.95,
            'top_k': 40,
            'max_output_tokens': 1024,
        }

        self.model = GenerativeModel(
            model_name=self.config.AGENT_MODEL,
            generation_config=generation_config,
            tools=[search_tool],
            system_instruction=(
                'Du bist der ScholarAgent. Beantworte Fachfragen präzise und ausschließlich auf Basis der vorhandenen Dokumente.\n'
                'Wenn die Information nicht in den Dokumenten steht, sag es offen.\n'
                'REGLER FÜR ZITATE:\n'
                "1. Fasse am Ende deiner Antwort alle verwendeten Dokumente in einer kurzen Liste 'Verwendete Quellen' zusammen und zitieren deine Aussagen im IEEE-Stil. Füge auch eine Seitenzahl zu der Quelle hinzu.\n"
            )
        )
        logger.info('Agent initialized with VertexAI tools.')

    def ask(self, question: str) -> str:
        """Sends a question to the LLM and handles potential tool calls recursively."""
        logger.info(f'Processing user question: {question}')
        chat = self.model.start_chat()
        response = chat.send_message(question)

        # Handle Funcion Call (Tool use)
        if response.candidates[0].content.parts[0].function_call:
            call = response.candidates[0].content.parts[0].function_call

            if call.name == 'search_docs':
                query_args = call.args['query']
                logger.info(f'Agent decided to call search_docs with: "{query_args}"')

                # Execute the actual search
                result_context = self.search_func(query_args)

                # Feed the search results back to the LLM
                response = chat.send_message(
                    Part.from_function_response(
                        name=call.name, response={'content': result_context}
                    )
                )

        logger.debug('Final answer generated by the agent')
        return response.text
